[package]
name = "motley"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.24.0"
glam = "0.23.0"
gltf = "1.0.0"
stb_image = "0.2.4"
criterion = "0.5.1"

[[bench]]
name = "performance"
harness = false

[[bin]]
name = "validate_benchmarks"
path = "scripts/validate_benchmarks.rs"